title: Tristan Hall
description: A collection of things I've built, projects I'm working on and cool stuff I'm interested in.
google_analytics: UA-17578082-1
show_downloads: true
theme: jekyll-theme-architect

gems:
  - jekyll-mentions
